// 백엔드: src/modules/order/order.const.ts 와 동일
export const ORDER_STATUS = {
  ORDER: 'ORDER',
  PAID: 'PAID',
  CONFIRMED: 'CONFIRMED',
  USER_CANCEL: 'USER_CANCEL',
  PLACE_CANCEL: 'PLACE_CANCEL',
  ADMIN_CANCEL: 'ADMIN_CANCEL',
  FAILED: 'FAILED',
};

export const ORDER_CURRENT_STATUS = {
  TODAY_PICKUP: 'TODAY_PICKUP',
  PICKED_UP: 'PICKED_UP',
};

export const ORDER_REVIEW_STATUS = {
  AVAILABLE: 'AVAILABLE',
  COMPLETED: 'COMPLETED',
  EXPIRED: 'EXPIRED',
  UNAVAILABLE: 'UNAVAILABLE',
};
